### PR TITLE
Adapt uwriter to latest clickable and morph web version

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by costales** [comment]
Hi,
Thanks a lot for the update!
I was playing with that 1 year ago and the app didn't work fine (keyboard
appears/hides playing clicking on Enter, on menus, etc...).
Is it working fine for you now?
Thanks!

**Comment by ghost** [comment]
> Hi, Thanks a lot for the update! I was playing with that 1 year ago and the app didn't work fine (keyboard appears/hides playing clicking on Enter, on menus, etc...). Is it working fine for you now? Thanks!

It is working much better. I am requesting you, please publish this useful app to ubuntu touch OS openstore once again after merging this request. By the way my real name is Quilty weavy, and you can find my active repositories in [gitlab](https://gitlab.com/quiltywea)

**Comment by maciek134** [comment]
Have you actually built the app this time, or is it yet another PR that just changes numbers? Looking at the commit messages from the web editor it seems kind of pointless to ask though...

**Comment by costales** [comment]
Hi, I hope to have time for reviewing it this weekend. Best regards

**Comment by ghost** [comment]
> Have you actually built the app this time, or is it yet another PR that just changes numbers? Looking at the commit messages from the web editor it seems kind of pointless to ask though...

Promise I have built and tested the app

**Comment by costales** [comment]
Hi @apy7hst !
I tested your branch and then I remember a few issues.

1st: I set as public this repo: https://github.com/costales/uwriter2 It has a few tries I did in the past.

2nd: With that uwriter2 repo & your repo I have these problems with a Volla phone (it has high resolution):

2.a: All is so smaller:


2.b: If I set [the scale into HTML](https://github.com/costales/uwriter2/blob/main/uwp/index.html#L5), appears this black box when the keyboard is opened, maybe is a CSS issue from my HTML code:


If someone has an idea about how to fix this, it's welcome!
Best regards.

**Comment by costales** [comment]
After a few tests, I think is this property which set the height of window at a wrong height: https://github.com/apy7hst/uwriter/blob/patch-1/qml/Main.qml#L31
If I set to true, the black box appears (because of wrong height) and if I set to false, the scroll is longer than window...
I would say it could be a system bug (?).

**Pull request closed without merging**
